export type DemoProductDef = {
  slug: string;
  sku: string;
  category: string;
  subcategory: string;
  nameRo: string;
  nameEn: string;
  shortRo: string;
  shortEn: string;
  descRo: string;
  descEn: string;
  price: number;
  compareAt?: number;
  cost: number;
  stock: number;
  weightGrams: number;
  lengthMm: number;
  widthMm: number;
  heightMm: number;
  pick?: boolean;
  featured?: boolean;
  isNew?: boolean;
  demoBestseller?: boolean;
  tags: string[];
  specsRo: string;
  specsEn: string;
  compatibilityRo: string;
  compatibilityEn: string;
  boxRo: string;
  boxEn: string;
  whyRo: string;
  whyEn: string;
  howRo: string;
  howEn: string;
  seoTitleRo: string;
  seoTitleEn: string;
  seoDescRo: string;
  seoDescEn: string;
};

function p(input: {
  slug: string;
  sku: string;
  category: string;
  subcategory: string;
  nameRo: string;
  nameEn: string;
  shortRo: string;
  shortEn: string;
  price: number;
  stock: number;
  tags: string[];
  compareAt?: number;
  pick?: boolean;
  featured?: boolean;
  isNew?: boolean;
  demoBestseller?: boolean;
  weightGrams?: number;
}): DemoProductDef {
  return {
    ...input,
    descRo: `${input.shortRo} Ales pentru uz zilnic, fără detalii de care nu ai nevoie.`,
    descEn: `${input.shortEn} Chosen for daily use, without details you will not need.`,
    cost: Math.round(input.price * 0.42),
    weightGrams: input.weightGrams ?? 180,
    lengthMm: 140,
    widthMm: 90,
    heightMm: 32,
    specsRo: "Materiale rezistente. Dimensiuni compacte. Finisaj mat.",
    specsEn: "Durable materials. Compact size. Matte finish.",
    compatibilityRo: "Utilizare generală. Verifică dimensiunile înainte de montaj.",
    compatibilityEn: "General use. Check dimensions before mounting.",
    boxRo: "1 × produs, 1 × ghid scurt.",
    boxEn: "1 × product, 1 × short guide.",
    whyRo: "L-am ales pentru că rezolvă o problemă concretă și rămâne în uz.",
    whyEn: "We chose it because it solves a concrete problem and stays in use.",
    howRo: "Îl instalezi o dată. Apoi îl folosești fără să te gândești la el.",
    howEn: "Set it up once. Then you use it without thinking about it.",
    seoTitleRo: `${input.nameRo} — RAVILO`,
    seoTitleEn: `${input.nameEn} — RAVILO`,
    seoDescRo: input.shortRo,
    seoDescEn: input.shortEn,
  };
}

export const DEMO_PRODUCTS: DemoProductDef[] = [
  p({
    slug: "ravilo-drive-mount",
    sku: "RAV-AUTO-001",
    category: "auto",
    subcategory: "auto-suporturi-telefon",
    nameRo: "RAVILO Drive Mount",
    nameEn: "RAVILO Drive Mount",
    shortRo: "Suport telefon pentru mașină, stabil pe drum.",
    shortEn: "Phone mount for the car, steady on the road.",
    price: 12900,
    stock: 20,
    pick: true,
    featured: true,
    tags: ["auto", "car", "mount", "phone", "drive"],
  }),
  p({
    slug: "ravilo-cardock-pro",
    sku: "RAV-AUTO-002",
    category: "auto",
    subcategory: "auto-suporturi-telefon",
    nameRo: "RAVILO CarDock Pro",
    nameEn: "RAVILO CarDock Pro",
    shortRo: "Dock auto mai ferm, pentru drumuri lungi.",
    shortEn: "A firmer car dock for longer drives.",
    price: 17900,
    compareAt: 19900,
    stock: 8,
    featured: true,
    tags: ["auto", "car", "dock", "phone"],
  }),
  p({
    slug: "ravilo-charge-65",
    sku: "RAV-AUTO-003",
    category: "auto",
    subcategory: "auto-incarcare",
    nameRo: "RAVILO Charge 65",
    nameEn: "RAVILO Charge 65",
    shortRo: "Încărcător auto 65W pentru telefon și laptop.",
    shortEn: "65W car charger for phone and laptop.",
    price: 14900,
    stock: 12,
    demoBestseller: true,
    tags: ["auto", "car", "charger", "charge", "usb-c"],
  }),
  p({
    slug: "ravilo-auto-organizer",
    sku: "RAV-AUTO-004",
    category: "auto",
    subcategory: "auto-organizare",
    nameRo: "RAVILO Auto Organizer",
    nameEn: "RAVILO Auto Organizer",
    shortRo: "Ordine între scaune, fără haos în cabină.",
    shortEn: "Order between the seats, without cabin clutter.",
    price: 9900,
    stock: 35,
    pick: true,
    tags: ["auto", "car", "organizer", "storage"],
  }),
  p({
    slug: "ravilo-car-cable-clip",
    sku: "RAV-AUTO-005",
    category: "auto",
    subcategory: "auto-accesorii-interior",
    nameRo: "RAVILO Car Cable Clip",
    nameEn: "RAVILO Car Cable Clip",
    shortRo: "Ține cablul de încărcare la îndemână, nu pe jos.",
    shortEn: "Keeps the charging cable at hand, not on the floor.",
    price: 4900,
    stock: 20,
    tags: ["auto", "car", "cable", "clip"],
  }),
  p({
    slug: "ravilo-dash-tray",
    sku: "RAV-AUTO-006",
    category: "auto",
    subcategory: "auto-organizare",
    nameRo: "RAVILO Dash Tray",
    nameEn: "RAVILO Dash Tray",
    shortRo: "Tavă antialunecare pentru chei, ochelari, card.",
    shortEn: "Non-slip tray for keys, glasses, cards.",
    price: 6900,
    stock: 5,
    isNew: true,
    tags: ["auto", "car", "tray", "dash"],
  }),
  p({
    slug: "ravilo-cabin-wipe-kit",
    sku: "RAV-AUTO-007",
    category: "auto",
    subcategory: "auto-curatenie",
    nameRo: "RAVILO Cabin Wipe Kit",
    nameEn: "RAVILO Cabin Wipe Kit",
    shortRo: "Kit compact de curățenie pentru habitaclu.",
    shortEn: "Compact cabin cleaning kit.",
    price: 7900,
    stock: 0,
    tags: ["auto", "car", "clean", "wipe"],
  }),
  p({
    slug: "ravilo-vent-mount",
    sku: "RAV-AUTO-008",
    category: "auto",
    subcategory: "auto-suporturi-telefon",
    nameRo: "RAVILO Vent Mount",
    nameEn: "RAVILO Vent Mount",
    shortRo: "Suport pe grila de ventilație, montaj rapid.",
    shortEn: "Vent mount with a quick clip.",
    price: 7900,
    stock: 12,
    tags: ["auto", "car", "mount", "vent", "phone"],
  }),
  p({
    slug: "ravilo-quickcharge-duo",
    sku: "RAV-AUTO-009",
    category: "auto",
    subcategory: "auto-incarcare",
    nameRo: "RAVILO QuickCharge Duo",
    nameEn: "RAVILO QuickCharge Duo",
    shortRo: "Două porturi auto, pentru șofer și pasager.",
    shortEn: "Two car ports, for driver and passenger.",
    price: 9900,
    compareAt: 11900,
    stock: 8,
    tags: ["auto", "car", "charger", "charge", "duo"],
  }),
  p({
    slug: "ravilo-seat-pocket",
    sku: "RAV-AUTO-010",
    category: "auto",
    subcategory: "auto-accesorii-interior",
    nameRo: "RAVILO Seat Pocket",
    nameEn: "RAVILO Seat Pocket",
    shortRo: "Buzunar pentru spătar: tablete, hărți, cabluri.",
    shortEn: "Seat-back pocket for tablets, maps, cables.",
    price: 8900,
    stock: 3,
    tags: ["auto", "car", "pocket", "organizer"],
  }),
  p({
    slug: "ravilo-flexcable-100w",
    sku: "RAV-TECH-001",
    category: "tech",
    subcategory: "tech-cabluri",
    nameRo: "RAVILO FlexCable 100W",
    nameEn: "RAVILO FlexCable 100W",
    shortRo: "Cablu USB-C 100W, flexibil, pentru telefon și laptop.",
    shortEn: "100W USB-C cable, flexible, for phone and laptop.",
    price: 7900,
    stock: 35,
    pick: true,
    featured: true,
    tags: ["tech", "cable", "usb-c", "charger", "flexcable"],
  }),
  p({
    slug: "ravilo-gan-45",
    sku: "RAV-TECH-002",
    category: "tech",
    subcategory: "tech-incarcatoare",
    nameRo: "RAVILO GaN 45",
    nameEn: "RAVILO GaN 45",
    shortRo: "Încărcător GaN 45W, mic pe priză.",
    shortEn: "45W GaN charger, small on the wall.",
    price: 12900,
    stock: 20,
    demoBestseller: true,
    tags: ["tech", "charger", "gan", "usb-c"],
  }),
  p({
    slug: "ravilo-gan-65",
    sku: "RAV-TECH-003",
    category: "tech",
    subcategory: "tech-incarcatoare",
    nameRo: "RAVILO GaN 65",
    nameEn: "RAVILO GaN 65",
    shortRo: "Încărcător GaN 65W pentru birou și drum.",
    shortEn: "65W GaN charger for desk and travel.",
    price: 17900,
    compareAt: 19900,
    stock: 12,
    pick: true,
    featured: true,
    tags: ["tech", "charger", "gan", "usb-c", "65"],
  }),
  p({
    slug: "ravilo-deskdock",
    sku: "RAV-TECH-004",
    category: "tech",
    subcategory: "tech-desk-setup",
    nameRo: "RAVILO DeskDock",
    nameEn: "RAVILO DeskDock",
    shortRo: "Dock de birou: telefonul stă, cablul dispare.",
    shortEn: "Desk dock: the phone stands, the cable disappears.",
    price: 19900,
    stock: 8,
    pick: true,
    isNew: true,
    tags: ["tech", "desk", "dock", "phone"],
  }),
  p({
    slug: "ravilo-magstand",
    sku: "RAV-TECH-005",
    category: "tech",
    subcategory: "tech-accesorii-telefon",
    nameRo: "RAVILO MagStand",
    nameEn: "RAVILO MagStand",
    shortRo: "Stand magnetic pentru telefon, pe birou sau noptieră.",
    shortEn: "Magnetic phone stand for desk or nightstand.",
    price: 9900,
    stock: 20,
    demoBestseller: true,
    tags: ["tech", "phone", "stand", "magnetic"],
  }),
  p({
    slug: "ravilo-cable-case",
    sku: "RAV-TECH-006",
    category: "tech",
    subcategory: "tech-cabluri",
    nameRo: "RAVILO Cable Case",
    nameEn: "RAVILO Cable Case",
    shortRo: "Husă pentru cabluri, adaptoare și stick-uri.",
    shortEn: "Case for cables, adapters and sticks.",
    price: 6900,
    stock: 35,
    tags: ["tech", "cable", "case", "travel"],
  }),
  p({
    slug: "ravilo-usb-c-hub-mini",
    sku: "RAV-TECH-007",
    category: "tech",
    subcategory: "tech-adaptoare",
    nameRo: "RAVILO USB-C Hub Mini",
    nameEn: "RAVILO USB-C Hub Mini",
    shortRo: "Hub compact USB-C pentru laptopul de zi cu zi.",
    shortEn: "Compact USB-C hub for the everyday laptop.",
    price: 14900,
    stock: 5,
    tags: ["tech", "hub", "adapter", "usb-c"],
  }),
  p({
    slug: "ravilo-desk-cable-rail",
    sku: "RAV-TECH-008",
    category: "tech",
    subcategory: "tech-desk-setup",
    nameRo: "RAVILO Desk Cable Rail",
    nameEn: "RAVILO Desk Cable Rail",
    shortRo: "Șină pentru cabluri sub birou. Birou fără fire.",
    shortEn: "Under-desk cable rail. A cable-free desk.",
    price: 12900,
    stock: 12,
    featured: true,
    tags: ["tech", "desk", "cable", "organizer"],
  }),
  p({
    slug: "ravilo-phone-stand-mini",
    sku: "RAV-TECH-009",
    category: "tech",
    subcategory: "tech-accesorii-telefon",
    nameRo: "RAVILO Phone Stand Mini",
    nameEn: "RAVILO Phone Stand Mini",
    shortRo: "Stand mic de telefon, unghi bun pentru apeluri.",
    shortEn: "Small phone stand, a good angle for calls.",
    price: 4900,
    stock: 0,
    tags: ["tech", "phone", "stand"],
  }),
  p({
    slug: "ravilo-charge-brick-30",
    sku: "RAV-TECH-010",
    category: "tech",
    subcategory: "tech-incarcatoare",
    nameRo: "RAVILO Charge Brick 30",
    nameEn: "RAVILO Charge Brick 30",
    shortRo: "Încărcător 30W, pentru telefonul de fiecare zi.",
    shortEn: "30W charger for the everyday phone.",
    price: 9900,
    compareAt: 11400,
    stock: 8,
    isNew: true,
    tags: ["tech", "charger", "charge", "usb-c"],
  }),
  p({
    slug: "ravilo-smart-plug-mini",
    sku: "RAV-HOME-001",
    category: "home",
    subcategory: "home-smart",
    nameRo: "RAVILO Smart Plug Mini",
    nameEn: "RAVILO Smart Plug Mini",
    shortRo: "Priză inteligentă compactă, fără scenarii complicate.",
    shortEn: "Compact smart plug, without complicated scenes.",
    price: 7900,
    stock: 20,
    pick: true,
    featured: true,
    tags: ["home", "smart", "plug", "smarthome"],
  }),
  p({
    slug: "ravilo-home-sensor",
    sku: "RAV-HOME-002",
    category: "home",
    subcategory: "home-smart",
    nameRo: "RAVILO Home Sensor",
    nameEn: "RAVILO Home Sensor",
    shortRo: "Senzor simplu pentru ușă sau fereastră.",
    shortEn: "A simple sensor for a door or window.",
    price: 9900,
    stock: 12,
    tags: ["home", "smart", "sensor"],
  }),
  p({
    slug: "ravilo-desk-tray",
    sku: "RAV-HOME-003",
    category: "home",
    subcategory: "home-birou",
    nameRo: "RAVILO Desk Tray",
    nameEn: "RAVILO Desk Tray",
    shortRo: "Tavă de birou pentru chei, pixuri și cabluri.",
    shortEn: "Desk tray for keys, pens and cables.",
    price: 12900,
    stock: 8,
    demoBestseller: true,
    tags: ["home", "desk", "tray", "organizer"],
  }),
  p({
    slug: "ravilo-drawer-grid",
    sku: "RAV-HOME-004",
    category: "home",
    subcategory: "home-organizare",
    nameRo: "RAVILO Drawer Grid",
    nameEn: "RAVILO Drawer Grid",
    shortRo: "Grilă ajustabilă pentru sertar.",
    shortEn: "Adjustable drawer grid.",
    price: 6900,
    stock: 35,
    tags: ["home", "organizer", "drawer"],
  }),
  p({
    slug: "ravilo-kitchen-hook-set",
    sku: "RAV-HOME-005",
    category: "home",
    subcategory: "home-bucatarie",
    nameRo: "RAVILO Kitchen Hook Set",
    nameEn: "RAVILO Kitchen Hook Set",
    shortRo: "Cârlige practice pentru bucătărie.",
    shortEn: "Practical kitchen hooks.",
    price: 4900,
    stock: 20,
    tags: ["home", "kitchen", "hook"],
  }),
  p({
    slug: "ravilo-desk-lamp-clip",
    sku: "RAV-HOME-006",
    category: "home",
    subcategory: "home-iluminare",
    nameRo: "RAVILO Desk Lamp Clip",
    nameEn: "RAVILO Desk Lamp Clip",
    shortRo: "Lampă cu clemă, lumină caldă pe birou.",
    shortEn: "Clip lamp, warm light on the desk.",
    price: 14900,
    compareAt: 16900,
    stock: 5,
    isNew: true,
    tags: ["home", "desk", "lamp", "light"],
  }),
  p({
    slug: "ravilo-entry-tray",
    sku: "RAV-HOME-007",
    category: "home",
    subcategory: "home-organizare",
    nameRo: "RAVILO Entry Tray",
    nameEn: "RAVILO Entry Tray",
    shortRo: "Tavă de hol pentru chei și carduri.",
    shortEn: "Hallway tray for keys and cards.",
    price: 7900,
    stock: 3,
    tags: ["home", "tray", "organizer"],
  }),
  p({
    slug: "ravilo-cable-box",
    sku: "RAV-HOME-008",
    category: "home",
    subcategory: "home-birou",
    nameRo: "RAVILO Cable Box",
    nameEn: "RAVILO Cable Box",
    shortRo: "Cutie pentru alimentatoare și prelungitoare.",
    shortEn: "Box for bricks and power strips.",
    price: 9900,
    stock: 0,
    tags: ["home", "cable", "box", "desk"],
  }),
  p({
    slug: "ravilo-travel-grid",
    sku: "RAV-TRV-001",
    category: "travel",
    subcategory: "travel-organizatoare",
    nameRo: "RAVILO Travel Grid",
    nameEn: "RAVILO Travel Grid",
    shortRo: "Organizator de bagaj, cuburi care se văd.",
    shortEn: "Luggage organizer, cubes you can actually see.",
    price: 9900,
    stock: 20,
    featured: true,
    demoBestseller: true,
    tags: ["travel", "organizer", "luggage", "packing"],
  }),
  p({
    slug: "ravilo-travel-adapter-pro",
    sku: "RAV-TRV-002",
    category: "travel",
    subcategory: "travel-adaptoare",
    nameRo: "RAVILO Travel Adapter Pro",
    nameEn: "RAVILO Travel Adapter Pro",
    shortRo: "Adaptor de priză pentru drum, USB-C inclus.",
    shortEn: "Travel plug adapter with USB-C.",
    price: 17900,
    compareAt: 19900,
    stock: 12,
    pick: true,
    tags: ["travel", "adapter", "charger", "plug"],
  }),
  p({
    slug: "ravilo-compact-tech-pouch",
    sku: "RAV-TRV-003",
    category: "travel",
    subcategory: "travel-tech",
    nameRo: "RAVILO Compact Tech Pouch",
    nameEn: "RAVILO Compact Tech Pouch",
    shortRo: "Pouch pentru cabluri, baterie și pașaport tehnic.",
    shortEn: "Pouch for cables, battery and travel tech.",
    price: 12900,
    stock: 8,
    isNew: true,
    tags: ["travel", "pouch", "tech", "cable"],
  }),
  p({
    slug: "ravilo-packing-sleeve",
    sku: "RAV-TRV-004",
    category: "travel",
    subcategory: "travel-bagaje",
    nameRo: "RAVILO Packing Sleeve",
    nameEn: "RAVILO Packing Sleeve",
    shortRo: "Husă subțire pentru haine, în cabină.",
    shortEn: "Thin packing sleeve for cabin clothes.",
    price: 6900,
    stock: 35,
    tags: ["travel", "luggage", "packing"],
  }),
  p({
    slug: "ravilo-tracker-sleeve",
    sku: "RAV-TRV-005",
    category: "travel",
    subcategory: "travel-avion",
    nameRo: "RAVILO Tracker Sleeve",
    nameEn: "RAVILO Tracker Sleeve",
    shortRo: "Husă pentru tracker, pe bagaj sau chei.",
    shortEn: "Tracker sleeve for luggage or keys.",
    price: 4900,
    stock: 20,
    tags: ["travel", "tracker", "holder", "luggage"],
  }),
  p({
    slug: "ravilo-cabin-bottle-sleeve",
    sku: "RAV-TRV-006",
    category: "travel",
    subcategory: "travel-avion",
    nameRo: "RAVILO Cabin Bottle Sleeve",
    nameEn: "RAVILO Cabin Bottle Sleeve",
    shortRo: "Husă pentru sticla din bagajul de cabină.",
    shortEn: "Sleeve for the bottle in a cabin bag.",
    price: 5900,
    stock: 5,
    tags: ["travel", "cabin", "bottle"],
  }),
  p({
    slug: "ravilo-travel-cable-roll",
    sku: "RAV-TRV-007",
    category: "travel",
    subcategory: "travel-tech",
    nameRo: "RAVILO Travel Cable Roll",
    nameEn: "RAVILO Travel Cable Roll",
    shortRo: "Rulou pentru cabluri, fără noduri în rucsac.",
    shortEn: "Cable roll, without knots in the pack.",
    price: 7900,
    compareAt: 8900,
    stock: 3,
    tags: ["travel", "cable", "tech", "organizer"],
  }),
  p({
    slug: "ravilo-edc-wallet",
    sku: "RAV-EDC-001",
    category: "edc",
    subcategory: "edc-portofele",
    nameRo: "RAVILO EDC Wallet",
    nameEn: "RAVILO EDC Wallet",
    shortRo: "Portofel subțire, carduri și cash, fără volum.",
    shortEn: "Slim wallet, cards and cash, without bulk.",
    price: 14900,
    stock: 12,
    pick: true,
    featured: true,
    tags: ["edc", "wallet", "everyday"],
  }),
  p({
    slug: "ravilo-key-clip",
    sku: "RAV-EDC-002",
    category: "edc",
    subcategory: "edc-carabiniere",
    nameRo: "RAVILO Key Clip",
    nameEn: "RAVILO Key Clip",
    shortRo: "Clip pentru chei, pe rucsac sau curea.",
    shortEn: "Key clip for a pack or belt.",
    price: 4900,
    stock: 35,
    demoBestseller: true,
    tags: ["edc", "key", "clip", "carabiner"],
  }),
  p({
    slug: "ravilo-everyday-pouch",
    sku: "RAV-EDC-003",
    category: "edc",
    subcategory: "edc-pouch-uri",
    nameRo: "RAVILO Everyday Pouch",
    nameEn: "RAVILO Everyday Pouch",
    shortRo: "Pouch de zi cu zi pentru cablu, carduri, bani.",
    shortEn: "Everyday pouch for a cable, cards, cash.",
    price: 9900,
    stock: 8,
    isNew: true,
    tags: ["edc", "pouch", "organizer"],
  }),
  p({
    slug: "ravilo-carabiner-duo",
    sku: "RAV-EDC-004",
    category: "edc",
    subcategory: "edc-carabiniere",
    nameRo: "RAVILO Carabiner Duo",
    nameEn: "RAVILO Carabiner Duo",
    shortRo: "Două carabiniere mici, pentru chei și pouch.",
    shortEn: "Two small carabiners, for keys and a pouch.",
    price: 6900,
    compareAt: 7900,
    stock: 20,
    tags: ["edc", "carabiner", "clip"],
  }),
  p({
    slug: "ravilo-pocket-organizer",
    sku: "RAV-EDC-005",
    category: "edc",
    subcategory: "edc-organizare",
    nameRo: "RAVILO Pocket Organizer",
    nameEn: "RAVILO Pocket Organizer",
    shortRo: "Organizer de buzunar: pix, card, cablu scurt.",
    shortEn: "Pocket organizer: pen, card, short cable.",
    price: 7900,
    stock: 0,
    tags: ["edc", "organizer", "pocket", "everyday"],
  }),
];

export const LEGACY_DEMO_SLUGS = [
  "demo-organizator-portbagaj",
  "demo-cablu-usb-c-100w",
  "demo-set-organizare-sertar",
  "demo-packing-cube",
  "demo-lanterna-edc",
];
